### PR TITLE
dje/master

### PR DESCRIPTION
**Pull request by davidjeddy**
Changes to docker and codeception integration
Docker: setup usage for docker override, nginx config examples for single and sub domain setups
Codeception: ADDED failed and screen capture extensions. Added phantomJs and set up acceptance tests to use it.

### CODE REVIEW

**Comment by davidjeddy** [comment]
This is a more comprehensive configuration for a docker environment for use in CI/CD processes.

**Comment by davidjeddy** [comment]
I know it's a larger PR it focuses on codeception testing and docker implementation. Can squash the commits if you like (I like seeing people's entire work process).

**Comment by davidjeddy** [comment]
Any chance on this bring approved or denied?

**Comment by trntv** [comment]
Can you remove _output and _generated files from PR? I'll merge it then.

**Comment by davidjeddy** [comment]
_support and _ouput should now only contain a .gitignore.
Moved Fixture helper from common/_support to common/_helper

**Comment by trntv** [comment]
https://github.com/davidjeddy/yii2-starter-kit/tree/4d5202cfe974e5a6b7c606f1cfe54da114d34ba2/tests/codeception/frontend/_output

**Comment by davidjeddy** [comment]
Alright, that should do it.

**Pull request merged**
