### PR TITLE
[WIP] Improve docker & vagrant provisioning.

### PR DESCRIPTION
**Pull request by ddinchev**
**This is work-in-progress PR, provide feedback but do not merge**

I'm trying to help simplify the structure of the repository and fix several problems with docker / vagrant provisioning.

- [x] `docker-compose.yml` should not include host IP. Host IP is `127.0.0.1` only for hosts with native docker support (Linux). Mac / Windows users need to use VM and have different host IP (like `192.168.99.100`) and the project instructions fail.
- [x] There is no point of commiting `.dist` files with default values and ignore the actual ones. In real projects, you want to have the real `.env` / `vhost.conf` etc file commited. Trying to maintain `.dist` files is error-prone as even if you commit changes, other project members that use the file without the `.dist` commit don't get the change and run into problems.
- [x] Everything related to Docker should go in `docker/` (except for `docker-compose.yml`). 
- [ ] Update the docs to reflect the changes.
- [ ] If we use `vagrant`, it should be used to facilitate `docker` provisioning, move everything related to it under `vagrant/` dir instead of the docs dir.

### CODE REVIEW

**Comment by XzAeRo** [comment]
> There is no point of commiting .dist files with default values and ignore the actual ones. **_In real projects_**, you want to have the real .env / vhost.conf etc file commited. 

I completely agree.

> Trying to maintain .dist files is error-prone as even if you commit changes, other project members that use the file without the .dist commit don't get the change and run into problems.

I don't agree, at least for this project. I mean, there should exist example files to get started and the `*.dist` files fulfill that need perfectly. Maybe the solution here is move those files to a `configs` directory, like what you're doing with Docker files.

**Comment by ddinchev** [comment]
@XzAeRo The `.env` / `vhost.conf` will be commited and will serve as example to get you started, in this repo included.

**Comment by ddinchev** [comment]
Actually I see the point of having initial `.dist` files but remove the non-dist files from `.gitignore` or at least give instructions in the docs that in real-world applications you would need to remove them from `.gitignore` and commit files with real values.

**Comment by trntv** [comment]
imho, we need some files with environment-specific settings. I don't see any other way (except "real" environment variables) to store them. Where do you want to store, for example, your local dsn connection?

**Comment by XzAeRo** [comment]
@ddinchev I was looking at the commits you made, and it's a fantastic work!
Do you need any help with the documentation?

**Comment by trntv** [comment]
Fixed in 2.3.0

**Pull request closed without merging**
