### PR TITLE
Fixed travis build and all tests to pass. Some additional work on console commands.

### PR DESCRIPTION
**Pull request by alfredleo**
This fixes travis error on github credentials and overal tests to pass.

### CODE REVIEW

**Comment by alfredleo** [comment]
Here we have almost all tests pass. Only functional SignupCest fails. I need some help. The difference is only in using PhpBrowser that passes and Yii2 module functional fails.

**Comment by alfredleo** [comment]
Tests should not rely on the data of migrations. We just need database structure. So this PR clears test database after applying migrations, using php tests/codeception/bin/yii app/truncate. Then adds all data for tests to run.
I need help with the functional test failing on SignupCest. The same thing works on acceptance SignupCest. You can check them cept run -d -c tests/codeception/frontend functional SignupCest and cept run -d -c tests/codeception/frontend acceptance SignupCest. First one runs with Yii2 module without server on http://localhost/frontend/web/index-test.php. Second one is run on the built in php server with PhpBrowser on http://localhost:8080/frontend/web/index-test.php. I think there is some cookie/session problem with the Yii2 module.

**Comment by davidjeddy** [comment]
@trntv Can we get this merged please. If you are in need of more contributors / maintainers I am happy to assist as well.

**Comment by alfredleo** [comment]
I am happy to fix anything that @trntv thinks is not right to accept PR.

**Comment by trntv** [comment]
@alfredleo fix this small issues i've commented and i'll be glad to merge this PR

**Comment by alfredleo** [comment]
@trntv can you please point me to this small issue, I can't see one.

**Comment by alfredleo** [comment]
All tests passed, new asset-packagist plugin updated. PR can be accepted now.

**Comment by alfredleo** [comment]
@trntv can you please merge this.

**Pull request merged**
