### PR TITLE
Minor style and bug fixes.

### PR DESCRIPTION
**Pull request by ddinchev**
* Bug fix in `SystemLog` model (there is no `backend\models\query\SystemLogQuery`).
* Multiple style fixes as per PHP PSR conventions.

### CODE REVIEW

**Comment by ddinchev** [comment]
Even in the change log, it's cited that the `EnumColumn` is in `common\components\grid`, where it should be (given it's a component). I changed all the referenced and namespaces to point to the moved one.

**Comment by trntv** [comment]
it was in components long time ago, then i moved it to ``common\grid`` :-)

the point is that in ``common\components`` should be components from here 
https://github.com/trntv/yii2-starter-kit/blob/master/common/config/base.php#L9
and some standalone modules, like ``maintenance``

So, i think we should leave only `keystorage`` and ``maintenance`` there and move other classes somewhere else.

**Comment by ddinchev** [comment]
Any suggestions where should we move other classes. In my opinion all non-major components should go under `components`. Something like this:
```
common/actions/...
common/assets/...
common/components/model/MultiModel.php
common/components/behaviours/...
common/components/grid/...
common/components/filesystem/...
common/components/log/...
common/components/keyStorage/...
common/components/maintenance/...
common/components/rbac/...
common/components/widgets/...
common/messages
common/migrations
common/models
common/runtime
common/validators
```

My argument is that such components (those that I've suggested to go under components) require attention much less often than the major ones. As such, they won't get in the way when the developer is looking for models, validators, migrations (something that happens all the time under usual app lifecycle). Also this will create the practice to put any rarely modified components under the `common/components` folder, otherwise any custom component a developer creates will go directly under `common/` and it will get messy.

I'd even put 'validators/` and 'actions/` under components.

However I respect your decision, if you suggest different consistent structure, I'd stick to that. But right now it's not very clear where to put new components when you extend something.

**Comment by trntv** [comment]
the most obvious way is to follow yii2 namespaces structure:
https://github.com/yiisoft/yii2/tree/master/framework

all "unclassified" clasess may be stored under ``base`` or ``app`` or ``lib`` or something like that.
IMHO, it was a yii1's habit to store everything in ``components``

**Comment by ddinchev** [comment]
You might be right that I still see `components` as the ones in `yii1`. I like root "base/" as structure reflecting that.

**Comment by trntv** [comment]
can you remove your EnumColumn changes? i'll merge your style fixes then

**Comment by ddinchev** [comment]
I'll remove it and make a project-wide style change (PHPStorm allows you to fix style in whole project) and push that PR later today.

**Comment by ddinchev** [comment]
I will create another pull request when I have time. Sorry for the delay.

**Pull request closed without merging**
