### PR TITLE
Improve Vagrant provisioning

### PR DESCRIPTION
**Pull request by XzAeRo**
- Improves Composer performance during provisioning (see[ Composer Troubleshooting](https://getcomposer.org/doc/articles/troubleshooting.md#xdebug-impact-on-composer)).
 - Copies `.env.dist` file only if doesn't exists.

### CODE REVIEW

**Comment by trntv** [comment]
I've just made some changes to vagrant files. Can your actualize your PR with current code?

**Comment by XzAeRo** [comment]
Ok, I'm on it

**Comment by XzAeRo** [comment]
Done!

**Comment by trntv** [comment]
i meant that there is not php5enmod, vagrant uses php7 :-)

**Comment by XzAeRo** [comment]
Hahah, sorry, will do it as soon I get home

**Comment by trntv** [comment]
nothing here?

**Pull request closed without merging**
